development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: simple_shop_development
  username: postgres
  password: london
  allow_concurrency: true
  pool: 5
  schema_search_path: "public, extensions, osm"

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: simple_shop_test
  username: postgres
  password: london
  allow_concurrency: true
  pool: 5
  schema_search_path: "public, extensions, osm"
   
production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: simple_shop_production
  username: postgres
  password: london
  allow_concurrency: true
  pool: 5
